#!/bin/bash


# ./createAndSubmitJobs.py -w rizki_LXBatch_BoostedTaggerValidation_cutFlow_usePruned_fjpt450_eta2p4_DoubleMuTag_50m200_tau0p5 -c btagvalidation_cfg.py -d rizki_datasetList_BoostedTaggerValidation_cutFlow_usePruned_fjpt450_eta2p4_DoubleMuTag_m50to200_tau0p5.txt -q cmscaf1nh
# ./createAndSubmitJobs.py -w rizki_LXBatch_BoostedTaggerValidation_cutFlow_usePruned_fjpt450_eta2p4_DoubleMuTag_50m200_tau0p7 -c btagvalidation_cfg.py -d rizki_datasetList_BoostedTaggerValidation_cutFlow_usePruned_fjpt450_eta2p4_DoubleMuTag_m50to200_tau0p7.txt -q cmscaf1nh
# ./createAndSubmitJobs.py -w rizki_LXBatch_BoostedTaggerValidation_cutFlow_usePruned_fjpt450_eta2p4_DoubleMuTag_50m200 -c btagvalidation_cfg.py -d rizki_datasetList_BoostedTaggerValidation_cutFlow_usePruned_fjpt450_eta2p4_DoubleMuTag_m50to200.txt -q cmscaf1nh
# ./createAndSubmitJobs.py -w rizki_LXBatch_BoostedTaggerValidation_cutFlow_usePruned_fjpt450_eta2p4_DoubleMuTag -c btagvalidation_cfg.py -d rizki_datasetList_BoostedTaggerValidation_cutFlow_usePruned_fjpt450_eta2p4_DoubleMuTag.txt -q cmscaf1nh
# ./createAndSubmitJobs.py -w rizki_LXBatch_BoostedTaggerValidation_cutFlow_usePruned_fjpt450_eta2p4_SingleMuTag -c btagvalidation_cfg.py -d rizki_datasetList_BoostedTaggerValidation_cutFlow_usePruned_fjpt450_eta2p4_SingleMuTag.txt -q cmscaf1nh
# ./createAndSubmitJobs.py -w rizki_LXBatch_BoostedTaggerValidation_cutFlow_usePruned_fjpt450_eta2p4 -c btagvalidation_cfg.py -d rizki_datasetList_BoostedTaggerValidation_cutFlow_usePruned_fjpt450_eta2p4.txt -q cmscaf1nh
# ./createAndSubmitJobs.py -w rizki_LXBatch_BoostedTaggerValidation_cutFlow_usePruned_fjpt450 -c btagvalidation_cfg.py -d rizki_datasetList_BoostedTaggerValidation_cutFlow_usePruned_fjpt450.txt -q cmscaf1nh
# ./createAndSubmitJobs.py -w rizki_LXBatch_BoostedTaggerValidation_cutFlow_usePruned -c btagvalidation_cfg.py -d rizki_datasetList_BoostedTaggerValidation_cutFlow_usePruned.txt -q cmscaf1nh
# 
# ./createAndSubmitJobs.py -w rizki_LXBatch_BoostedTaggerValidation_cutFlow_BTagMu_QCDMuEnriched_usePruned_fjpt330_eta2p4_SingleMuTag -c btagvalidation_cfg.py -d rizki_datasetList_BoostedTaggerValidation_cutFlow_BTagMu_QCDMuEnriched_usePruned_fjpt330_eta2p4_SingleMuTag.txt -q cmscaf1nh
# ./createAndSubmitJobs.py -w rizki_LXBatch_BoostedTaggerValidation_cutFlow_BTagMu_QCDMuEnriched_usePruned_fjpt330_eta2p4_DoubleMuTag -c btagvalidation_cfg.py -d rizki_datasetList_BoostedTaggerValidation_cutFlow_BTagMu_QCDMuEnriched_usePruned_fjpt330_eta2p4_DoubleMuTag.txt -q cmscaf1nh
# ./createAndSubmitJobs.py -w rizki_LXBatch_BoostedTaggerValidation_cutFlow_BTagMu_QCDMuEnriched_usePruned_fjpt330_eta2p4_DoubleMuTag_50m200 -c btagvalidation_cfg.py -d rizki_datasetList_BoostedTaggerValidation_cutFlow_BTagMu_QCDMuEnriched_usePruned_fjpt330_eta2p4_DoubleMuTag_m50to200.txt -q cmscaf1nh
# ./createAndSubmitJobs.py -w rizki_LXBatch_BoostedTaggerValidation_cutFlow_BTagMu_QCDMuEnriched_usePruned_fjpt330_eta2p4_DoubleMuTag_50m200_tau0p7 -c btagvalidation_cfg.py -d rizki_datasetList_BoostedTaggerValidation_cutFlow_BTagMu_QCDMuEnriched_usePruned_fjpt330_eta2p4_DoubleMuTag_m50to200_tau0p7.txt -q cmscaf1nh
#./createAndSubmitJobs.py -w rizki_LXBatch_BoostedTaggerValidation_cutFlow_BTagMu_QCDMuEnriched_usePruned_fjpt330_eta2p4_DoubleMuTag_50m200_tau0p5 -c btagvalidation_cfg.py -d rizki_datasetList_BoostedTaggerValidation_cutFlow_BTagMu_QCDMuEnriched_usePruned_fjpt330_eta2p4_DoubleMuTag_m50to200_tau0p5.txt -q cmscaf1nh

./createAndSubmitJobs.py -w rizki_LXBatch_BoostedTaggerValidation_DoubleMuonTagged_50m200_tau21-1p0_fj450_usePruned_debug_ptRatioCut -c btagvalidation_cfg.py -d rizki_datasetList_BoostedTaggerValidation_DoubleMuonTagged_50m200_tau21-1p0_fj450_usePruned.txt -q cmscaf1nh
# ./createAndSubmitJobs.py -w rizki_LXBatch_BoostedTaggerValidation_DoubleMuonTagged_50m200_tau21-1p0_fj450_usePruned_debug -c btagvalidation_cfg.py -d rizki_datasetList_BoostedTaggerValidation_DoubleMuonTagged_50m200_tau21-1p0_fj450_usePruned.txt -q cmscaf1nh

# ./createAndSubmitJobs.py -w rizki_LXBatch_BoostedTaggerValidation_DoubleMuonTagged_50m200_tau21-1p0_fj450_usePruned -c btagvalidation_cfg.py -d rizki_datasetList_BoostedTaggerValidation_DoubleMuonTagged_50m200_tau21-1p0_fj450_usePruned.txt

#./createAndSubmitJobs.py -w rizki_LXBatch_Jobs_fatJetPtMin_450_tau-0p5  -c btagvalidation_cfg.py -d rizki_datasetList2015_2ndTime_withJetPtWeight_fj450.txt 

# ./createAndSubmitJobs.py -w rizki_LXBatch_Jobs_SingleMuonTagged_tau21-0p5_fj450 -c btagvalidation_cfg.py -d rizki_datasetList2015_SingleMuonTagged_tau21-0p5_fj450.txt
# ./createAndSubmitJobs.py -w rizki_LXBatch_Jobs_fatJetPtMin_450_tau-0p5  -c btagvalidation_cfg.py -d rizki_datasetList2015_fj450.txt 
# ./createAndSubmitJobs.py -w rizki_LXBatch_BoostedTaggerValidation_DoubleMuonTagged_50m200_tau21-1p0_fj450 -c btagvalidation_cfg.py -d rizki_datasetList_BoostedTaggerValidation_DoubleMuonTagged_50m200_tau21-1p0_fj450.txt

#./createAndSubmitJobs.py -w rizki_LXBatch_Jobs_fatJetPtMin_425_tau-0p5  -c btagvalidation_cfg.py -d rizki_datasetList2015_2ndTime_withJetPtWeight.txt 
#./createAndSubmitJobs.py -w rizki_LXBatch_BoostedTaggerValidation_DoubleMuonTagged_50m200_tau21-1p0_fj425 -c btagvalidation_cfg.py -d rizki_datasetList_BoostedTaggerValidation_DoubleMuonTagged_50m200_tau21-1p0_fj425.txt
#./createAndSubmitJobs.py -w rizki_LXBatch_BoostedTaggerValidation_DoubleMuonTagged_50m200_tau21-1p0_fj330_newTriggerPath -c btagvalidation_cfg.py -d rizki_datasetList_BoostedTaggerValidation_DoubleMuonTagged_50m200_tau21-1p0_fj330_newTriggerPath.txt
#./createAndSubmitJobs.py -w rizki_LXBatch_Jobs_fatJetPtMin_425_tau-0p5  -c btagvalidation_cfg.py -d rizki_datasetList2015.txt 
#./createAndSubmitJobs.py -w rizki_LXBatch_Jobs_SingleMuonTagged_tau21-0p5 -c btagvalidation_cfg.py -d rizki_datasetList2015_SingleMuonTagged_tau21-0p5.txt
